apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: jtran
spec:
  type: NodePort
  selector:
    app: app
  ports:
    - name: "5000"
      port: 5000
      targetPort: <TARGET PORT>
